#!/usr/bin/env bash

cur=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo 'Current state: ' $cur
echo 'Change?'
select yn in "Yes" "No"; do
    case $yn in
        Yes )
	    if [ $cur == 'performance' ]
	    then
		echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
	    else
		echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
	    fi;
	    
	    break;;
        No ) break;;
    esac
done

new=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo 'New state: ' $new

exit 0
